// <auto-generated />
namespace DrugStockWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class change_manufacture_id_field : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_manufacture_id_field));
        
        string IMigrationMetadata.Id
        {
            get { return "202310281605541_change_manufacture_id_field"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
