// <auto-generated />
namespace DrugStockWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_store_to_invoice_and_receipt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_store_to_invoice_and_receipt));
        
        string IMigrationMetadata.Id
        {
            get { return "202311221658140_add_store_to_invoice_and_receipt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
