// <auto-generated />
namespace DrugStockWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addStoreReceiptTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addStoreReceiptTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202311011512590_add-StoreReceipt-Table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
