// <auto-generated />
namespace DrugStockWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class update_invoice_table3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_invoice_table3));
        
        string IMigrationMetadata.Id
        {
            get { return "202311081201571_update_invoice_table3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
