// <auto-generated />
namespace DrugStockWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updateProductTablenullabelgeneric : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateProductTablenullabelgeneric));
        
        string IMigrationMetadata.Id
        {
            get { return "202310201548438_update-Product-Table-nullabel-generic"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
