// <auto-generated />
namespace DrugStockWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Remoce_manufacture_field_from_product : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Remoce_manufacture_field_from_product));
        
        string IMigrationMetadata.Id
        {
            get { return "202310281619397_Remoce_manufacture_field_from_product"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
