// <auto-generated />
namespace DrugStockWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addInvoiceReturnBusinnessPArtnerId2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addInvoiceReturnBusinnessPArtnerId2));
        
        string IMigrationMetadata.Id
        {
            get { return "202401121112184_add-InvoiceReturn-BusinnessPArtnerId2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
