// <auto-generated />
namespace DrugStockWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addeconomicalcode : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addeconomicalcode));
        
        string IMigrationMetadata.Id
        {
            get { return "202401301904494_add-economical-code"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
