// <auto-generated />
namespace DrugStockWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Adddescription_to_Province : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Adddescription_to_Province));
        
        string IMigrationMetadata.Id
        {
            get { return "202401161130340_Add-description_to_Province"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
