// <auto-generated />
namespace DrugStockWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addsomelogtypes4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addsomelogtypes4));
        
        string IMigrationMetadata.Id
        {
            get { return "202508230912424_add-some-log-types4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
