// <auto-generated />
namespace DrugStockWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_is_seen_to_log : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_is_seen_to_log));
        
        string IMigrationMetadata.Id
        {
            get { return "202503011712142_add_is_seen_to_log"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
