// <auto-generated />
namespace DrugStockWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class password_needed_charcters : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(password_needed_charcters));
        
        string IMigrationMetadata.Id
        {
            get { return "202504091836541_password_needed_charcters"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
