// <auto-generated />
namespace DrugStockWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _202503021504356_addsomeotherlogtypes3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_202503021504356_addsomeotherlogtypes3));
        
        string IMigrationMetadata.Id
        {
            get { return "202503310926456_202503021504356_add-some-other-log-types3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
