// <auto-generated />
namespace DrugStockWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class security_setting_logout_inactive_session : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(security_setting_logout_inactive_session));
        
        string IMigrationMetadata.Id
        {
            get { return "202511070703301_security_setting_logout_inactive_session"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
