// <auto-generated />
namespace DrugStockWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_some_log_types : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_some_log_types));
        
        string IMigrationMetadata.Id
        {
            get { return "202504121838374_add_some_log_types"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
