// <auto-generated />
namespace DrugStockWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class somePermissionAdded7 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(somePermissionAdded7));
        
        string IMigrationMetadata.Id
        {
            get { return "202509251618150_somePermissionAdded7"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
