// <auto-generated />
namespace DrugStockWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class active_2fa : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(active_2fa));
        
        string IMigrationMetadata.Id
        {
            get { return "202505020515150_active_2fa"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
