// <auto-generated />
namespace DrugStockWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class set_creator_nullable_in_log : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(set_creator_nullable_in_log));
        
        string IMigrationMetadata.Id
        {
            get { return "202501191045371_set_creator_nullable_in_log"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
