using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using DrugStockWeb.Models.LogSystem;

namespace DrugStockWeb.Models.Constanct
{
    public static class LogTypeValues
    {
        public const int Login = 1;
        public const int CreateStore = 2;
        public const int EditStore = 3;
        public const int UserTemporaryBlocked = 4;
        public const int DeleteStore = 5;
        public const int ListStore = 6;
        public const int CreateProductGroup = 7;
        public const int EditProductGroup = 8;
        public const int ListProductGroup = 9;
        public const int DeleteProductGroup = 10;
        public const int CreateProductSubGroup = 11;
        public const int EditProductSubGroup = 12;
        public const int ListProductSubGroup = 13;
        public const int DeleteProductSubGroup = 14;
        public const int CreateManufacture = 15;
        public const int EditManufacture = 16;
        public const int ListManufacture = 17;
        public const int DeleteManufacture = 18;
        public const int CreateProduct = 19;
        public const int EditProduct = 20;
        public const int ListProduct = 21;
        public const int DeleteProduct = 22;
        public const int CreateBusinessPartnerGroup = 23;
        public const int EditBusinessPartnerGroup = 24;
        public const int ListBusinessPartnerGroup = 25;
        public const int DeleteBusinessPartnerGroup = 26;
        public const int CreateBusinessPartner = 27;
        public const int EditBusinessPartner = 28;
        public const int ListBusinessPartner = 29;
        public const int DeleteBusinessPartner = 30;
        public const int ArchiveBusinessPartner = 31;
        public const int UnArchiveBusinessPartner = 32;
        public const int CreateStoreReceipt = 33;
        public const int EditStoreReceipt = 34;
        public const int ListStoreReceipt = 35;
        public const int DeleteStoreReceipt = 36;
        public const int ConfirmStoreReceipt = 37;
        public const int PrintStoreReceipt = 38;
        public const int CreateStoreReceiptReturn = 39;
        public const int EditStoreReceiptReturn = 40;
        public const int ListStoreReceiptReturn = 41;
        public const int DeleteStoreReceiptReturn = 42;
        public const int ConfirmStoreReceiptReturn = 43;
        public const int CreateInvoice = 44;
        public const int EditInvoice = 45;
        public const int ListInvoice = 46;
        public const int DeleteInvoice = 47;
        public const int ConfirmInvoice = 48;
        public const int PrintInvoice = 49;
        public const int CreateInvoiceReturn = 50;
        public const int EditInvoiceReturn = 51;
        public const int ListInvoiceReturn = 52;
        public const int DeleteInvoiceReturn = 53;
        public const int ConfirmInvoiceReturn = 54;
        public const int DisposeInvoiceReturn = 55;
        public const int ListLog = 56;
        public const int EditSecuritySetting = 57;
        public const int CreateRole = 58;
        public const int EditRole = 59;
        public const int RemoveRole = 60;
        public const int ListRole = 61;
        public const int AddOrRemovePermissionToRole = 62;
        public const int CreateUser = 63;
        public const int EditUser = 64;
        public const int ListUser = 65;
        public const int DeleteUser = 66;
        public const int ListOnlineUser = 67;
        public const int UserChangePassword = 68;
        public const int ReportStoreReceipt = 69;
        public const int ReportInvoice = 70;
        public const int ReportStockBalance = 71;
        public const int ReportDisposeStockBalance = 72;
        public const int CreateStoreReceiptDetail = 73;
        public const int EditStoreReceiptDetail = 74;
        public const int DeleteStoreReceiptDetail = 75;
        public const int CreateStoreReceiptDetailReturn = 76;
        public const int EditStoreReceiptDetailReturn = 77;
        public const int CreateInvoiceDetail = 78;
        public const int EditInvoiceDetail = 79;
        public const int DeleteInvoiceDetail = 80;
        public const int CreateInvoiceDetailReturn = 81;
        public const int EditInvoiceDetailReturn = 82;
        public const int DeleteInvoiceDetailReturn = 83;
        public const int PrintStoreReceiptReport = 84;
        public const int PrintInvoiceReport = 85;
        public const int PrintStoreBalance = 86;
        public const int PrintDisposeStoreReport = 87;
        public const int ConfirmInvoiceByAccounting = 88;
        public const int CardexReport = 89;
        public const int PrintCardexReport = 90;
        public const int ChangeSecuritySetting = 91;
        public const int LogTableIsDeleted = 92;
        public const int AddRoleToUser = 93;
        public const int ChangRoleOfUser = 94;
        public const int AddStoreTouser = 95;
        public const int RemoveStoreFromUser = 96;
        public const int LogOff = 97;
        public const int UnActiveUser = 98;
        public const int ActiveUser = 99;
        public const int ForceLogOutUser = 100;
        public const int ShowOnlineUserList = 101;/////created
        public const int ExceedLogThreshold = 102;
        public const int EnterForbiddenInput = 103;
        public const int UnknownError = 104;
        public const int AddBlackListIp = 105;
        public const int RemoveBlackListIp = 106;
        public const int ShowBlackListIp = 107;
        //public const int ExceedLogThresholdLogSeen = 108;
        public const int DatabaseManipulatedAlert = 108;
        public const int DatabaseManipulatedAdminSeen = 109;
        public const int LogCountMaxExceed = 110;
        public const int LogCountMaxExceed1AlertSeen = 111;
        public const int LogOffUserByInactive = 112;
        public const int LogOffUserByChanges = 113;
        public const int LogOffUserByConcurrentSessions = 114;
        public const int FailedEmailVerifyCode = 115;
        public const int LogOffUserByChangeIp = 116;


    }
}